version: "3.7"

services:
  vrising:
    image: ghcr.io/njanke96/v-rising-wine-docker-image
    container_name: v-rising
    restart: unless-stopped
    environment:
      # Host settings
      - VR_NAME="My V Rising Server"
      - VR_DESCRIPTION="Role playing server. Reset every Monday. Be nice."
      - VR_SAVE_NAME
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27016:27016/tcp
      - 27016:27016/udp
      - 25575:25575/tcp
    volumes:
      - ./data:/data
